### ISSUE TITLE
How to run project

### ISSUE THREAD

**Issue by arturparaschiv** [brescia123/sKanner#3]
Hi, I'm trying to run your project, but I cant. Can you help me please?

Give please your contact e-mail.

Best Regards,

Artur.

**Comment by brescia123** [comment]
Hi, I'm sorry but the library is not ready yet, I'll update the README to clarify it. 
Feel free to open an issue if you still have problems when the library will reach 1.0.0.

**Comment by ghost** [comment]
Thanks!
